### ISSUE TITLE
Ошибка в Render при использовании дополнительного провайдера

### ISSUE THREAD

**Issue by Sleuthhound** [bzick/fenom#128]
Попробовал работу с дополнительными провайдерами. Заметил, что при использовании флага Fenom::AUTO_RELOAD возникает ошибка в методе isValid() класса Render:
Notice:  Undefined offset: 0 in Fenom/Render.php on line 179

Пример кода:
```php
require 'src/Fenom.php';
Fenom::registerAutoload('src');

$view = new Fenom(new Fenom\Provider('view'));
$view->setCompileDir('cache');
$view->setOptions(Fenom::AUTO_RELOAD);

$view->addProvider('test', new Fenom\Provider('test'));
$view->display('test:test.tpl', array());
```
Значение при выполнении:
```php
[_depends:protected] => Array (
    [test] => Array (
        [test:test.tpl] => 1420376538
    )
)
```

**Comment by bzick** [comment]
Опа, да, ошибочка там

**Comment by Sleuthhound** [comment]
Версия 2.4.2
Наблюдается ошибка Render::isValid() -> Provider::getLastModified() -> Provider::getTemplatePath()

Из класса Render
```php
...
$provider->getLastModified(key($templates))
...
```
key($templates) принимает например значение test:test.tpl, как следствие Provider::getTemplatePath() вызывает исключение 'Template test:test.tpl not found'
