### ISSUE TITLE
Cовместимость со smarty

### ISSUE THREAD

**Issue by f0mich** [bzick/fenom#129]
Пытаюсь перейти со смарти, наткнулся на проблему не полной совместимости со смарти.
например синтаксис for в smarty 
{for $i=0 to 3}
{/for}
что приводит к фечному циклу в феноме т.к. феном хочет to=3
имхо можно прийти к полной совемстимости и это не потребует особых дополнительный затрат.
с токинайзерами разбираться лень, но, например, если в файл Compiler.php в функцию forOpen
после 
```php
        $p   = $scope->tpl->parseParams($tokens, $p);
```
добавить
```php
		$k = array_keys($p);
		$kc = count($k);
		for($i=0; $i<$kc; $i++)
			if (!is_numeric($k[$i]) and $p[$k[$i]]==="true" and isset($k[$i+1]) and is_numeric($k[$i+1]))
			{
				$p[$k[$i]] = $p[$k[$i+1]];
				$i++;
			}
```
то будет совместимый со смарти синтаксис.

**Comment by bzick** [comment]
Это похоже на ошибку. Так не должно быть, шаг по умолчанию 1. Я гляну что не так

**Comment by f0mich** [comment]
шаг - 1, а вот максимальное значение true

**Comment by f0mich** [comment]
Так же столкнулся с еще одной проблемкой - разный синтаксис у смарти немного другой синтаксис в теге {include} (я говорю исключительно про базовые вещи которые используют большенство, без всяких наследований и т.д.) 
у смарти перед названием файла может стоять file= может тоже стоит сделать это необязательным параметром? а то столкнулся - пришлось переписовать кучу шаблонов.
И еще в смарти есть удобный параметр assign который вместо вывода -  ассайнит в переменную. имхо тоже очень легко можно реализовать.

**Comment by f0mich** [comment]
и еще 
/* modules/orders//admin/calc//list.html:27: {$itemid=$tmp.id} */
 echo $var["itemid"] = $var["tmp"]["id"]; ?>
тоже совмем кононичное поведение... мне же присвоить надо, а не показать результат.

**Comment by bzick** [comment]
По поводу совместимости со smarty у меня выделен отдельный проект https://github.com/bzick/fenom-extra. Не все там ладно, конечно, но главное начать)

**Comment by bzick** [comment]
Присвоение делается через `{set $itemid = $tmp.id}`

**Comment by f0mich** [comment]
ну просто мне не совсем понятно зачем ставить экстру если эти функции не противоречут основному функционалу, но при этом дают совместимость.... и реализовать их можно небольшими изменениями.
Имхо присваивание в смарти сделано правильние. я обычно присваиваю что-то для того чтоб в в дальнейшей логике шаблона было удобнее обратиться к какому-нить глобоковложенному массиву, а не для того чтоб их сразу показать... так что не понимаю зачем когда пишешь {$a=2} он выполняет присваивание и выводит результат.
ну дело конечно хозяйское...

**Comment by bzick** [comment]
Не нужно перегружать движок. Что бы добиться полной совместимости со смарти2 (да и со смарти3 тоже есть расхождения) надо очень много переделать, изменить и сломать обратную своместимость. Это при том что совместимость со смарти не всем нужна. Поэтому было решено вынести отдельным расширением к Fenom, тому кому надо сами подключать нужную совместимость с чем-либо. 
У Fenom есть присвоение с выводом и просто присвоение. Поэтому есть {$title = $text.title|truncate}  и {set $title = $text.title|truncate}

**Comment by bzick** [comment]
Итак, по [документации](https://github.com/bzick/fenom/blob/master/docs/ru/tags/for.md) надо писать `to=3`. О более простом варианте я подумаю, их несколько `{for $i=0 to 3}`,  `{for $i=0..3}`, {foreach 0..3 as $i} (тогда {for} становится атавизмом).
