### ISSUE TITLE
Inconsistent codestyle

### ISSUE THREAD

**Issue by creocoder** [bzick/fenom#13]
For example:

```
$scope["else"]
```

can be replaced with

```
$scope['else']
```

Why you use `"` without interpolation needs? Its:

- slower (php engine checks if there is any interpolated vars)
- make code style inconsistent

Can you replace all `"` with `'` in cases when you do NOT need interpolation? Thanks.

**Comment by bzick** [comment]
is not a problem and there is no appreciable profit. So, if nobody wants to do - close
