### ISSUE TITLE
Ошибка в Render при использовании дополнительного провайдера 2.4.2

### ISSUE THREAD

**Issue by Sleuthhound** [bzick/fenom#132]
https://github.com/bzick/fenom/issues/128
Наблюдается ошибка Render::isValid() -> Provider::getLastModified() -> Provider::getTemplatePath()

Из класса Render
```php
...
$provider->getLastModified(key($templates))
...
```
key($templates) возвращает, например, значение test:test.tpl, как следствие Provider::getTemplatePath() вызывает исключение 'Template test:test.tpl not found'

**Comment by bzick** [comment]
А можете скинуть скомпиленный шаблон на мой email?

**Comment by bzick** [comment]
Хотя уже нашел баг
